# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRADlabsheet111():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_rADlabsheet111(self):
    self.driver.get("https://demoqa.com/automation-practice-form")
    self.driver.set_window_size(974, 1032)
    self.driver.find_element(By.ID, "firstName").click()
    self.driver.find_element(By.ID, "firstName").send_keys("Gayathra")
    self.driver.find_element(By.ID, "lastName").click()
    self.driver.find_element(By.ID, "lastName").send_keys("Dissanayake")
    self.driver.find_element(By.ID, "userEmail").click()
    self.driver.find_element(By.ID, "userEmail").send_keys("gayathradissa@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".custom-radio:nth-child(1)").click()
    self.driver.find_element(By.ID, "userNumber").click()
    self.driver.find_element(By.CSS_SELECTOR, ".custom-radio:nth-child(1) > .custom-control-label").click()
    self.driver.find_element(By.ID, "userNumber").click()
    self.driver.find_element(By.ID, "userNumber").send_keys("0702604647")
    self.driver.find_element(By.ID, "dateOfBirth").click()
    self.driver.find_element(By.CSS_SELECTOR, ".react-datepicker__current-month").click()
    self.driver.find_element(By.CSS_SELECTOR, ".react-datepicker__current-month").click()
    self.driver.find_element(By.CSS_SELECTOR, ".react-datepicker__year-select").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".react-datepicker__year-select")
    dropdown.find_element(By.XPATH, "//option[. = '2000']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".react-datepicker__month-select").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".react-datepicker__month-select")
    dropdown.find_element(By.XPATH, "//option[. = 'March']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".react-datepicker__day--031").click()
    self.driver.find_element(By.CSS_SELECTOR, ".subjects-auto-complete__value-container").click()
    self.driver.find_element(By.ID, "subjectsInput").send_keys("Rapid Application Development")
    self.driver.find_element(By.CSS_SELECTOR, ".custom-checkbox:nth-child(2) > .custom-control-label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".custom-checkbox:nth-child(3) > .custom-control-label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".subjects-auto-complete__value-container").click()
    self.driver.find_element(By.ID, "subjectsInput").send_keys("RAD")
    self.driver.find_element(By.ID, "currentAddress").click()
    self.driver.find_element(By.ID, "currentAddress").click()
    self.driver.find_element(By.ID, "currentAddress").send_keys("Post office quarters, Maharagama")
    self.driver.find_element(By.ID, "state").click()
    self.driver.find_element(By.ID, "react-select-3-option-0").click()
    self.driver.find_element(By.ID, "city").click()
    self.driver.find_element(By.ID, "react-select-4-option-1").click()
    self.driver.find_element(By.CSS_SELECTOR, "#close-fixedban > img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-12:nth-child(3)").click()
    self.driver.find_element(By.ID, "submit").click()
    element = self.driver.find_element(By.ID, "submit")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "closeLargeModal").click()
  
